signup/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('trips.urls'), name='trips'),
]

# admin.site.site_header = "管理人員介面"
# admin.site.site_title = "UMSRA Admin Portal"
# admin.site.index_title = "Welcome to UMSRA Researcher Portal"

admin.site.site_header = "管理人員頁面"
admin.site.site_title = "管理人員"
admin.site.site_url = "https://203.145.195.202:11111/admin/trips/visit_logs/"
admin.site.index_title = "訪客簽到系統管理"

signup/trips/urls.py
#_*_coding:utf8_*_
from django.urls import path
from .views import login, logout, home, checkID, addID , confirm, logout_confirm
urlpatterns = [
	path('', home, name='home'),
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
    path('checkID',checkID, name='checkID'),
    path('addID', addID, name='addID'),
    path('confirm', confirm, name="confirm"),
    path('logout_confirm', logout_confirm, name="logout_confirm" )
]

signup/trips/models.py
from django.db import models
import django.utils.timezone as timezone

# Create your models here.

class Organizations(models.Model):
	org_name = models.CharField(verbose_name="公司名稱",max_length = 50)
	FAX = models.CharField(verbose_name="傳真號碼",max_length = 20)
	class Meta:
		verbose_name_plural = "公司資訊"
	def __str__(self):
		return self.org_name
		
class Visitors(models.Model):
	name = models.CharField(verbose_name="訪客姓名",max_length = 20)
	phone_number = models.CharField(verbose_name="電話號碼",max_length = 10, default = '0912345678')
	email = models.EmailField(verbose_name="電子郵件",default='example@gmail.com')
	personal_ID = models.CharField(verbose_name="身分證字號",max_length = 10,blank = True)
	org_ID = models.ForeignKey(Organizations, on_delete=models.CASCADE, null=True,verbose_name="公司名稱")
	class Meta:
		verbose_name_plural = "個人資訊"
	def __str__(self):
		return self.name

class Visit_logs(models.Model):
    name = models.ForeignKey(Visitors, on_delete=models.CASCADE, null=True,verbose_name="訪客姓名",editable=False)
    # name = models.TextField(verbose_name="訪客姓名",max_length = 200,editable=False)
    company = models.ForeignKey(Organizations, on_delete=models.CASCADE, null=True,verbose_name="公司名稱",editable=False)
    # company = models.TextField(verbose_name="公司名稱",max_length = 30,editable=False,default="")

    class Purpose(object):
        one = 0
        two = 1

    PURPOSE_CHOICES = (
        (Purpose.one, '技術性作業'), 
        (Purpose.two, '拜訪及會議討論'),
    )

    purpose = models.PositiveSmallIntegerField(
    	verbose_name="進入目的",
        choices = PURPOSE_CHOICES,
    )


    class Visit_area(object):
        office = 0
        computer = 1

    VISIT_AREA_CHOICES = (
        (Visit_area.office, '辦公區域'),
        (Visit_area.computer, '電腦機房'),
    )

    visit_area = models.PositiveSmallIntegerField(
    	verbose_name="進出區域",
        choices = VISIT_AREA_CHOICES,
    )


    class Host(object):
        blhuang = 0
        cpchuang = 1
        yuking = 2
        lhchang = 3
        hdwu = 4
        cmchung = 5
        ktwu = 6
        cmhuang = 7
        ytlin = 8
        chyen = 9
        gracechuang = 10
        cjhsu = 11
        hsychang = 12

    HOST_CHOICES = (
        (Host.blhuang, '黃百立'),
        (Host.cpchuang, '莊峻沛'),
        (Host.yuking, '金禹天'),
        (Host.lhchang, '張麗環'),
        (Host.hdwu, '吳宏德'),
        (Host.cmchung, '鍾振明'),
        (Host.ktwu, '吳坤達'),
        (Host.cmhuang, '黃俊銘'),
        (Host.ytlin, '林彥廷'),
        (Host.chyen, '顏志宏'),
        (Host.gracechuang, '莊嘉怡'),
        (Host.cjhsu, '許純茹'),
        (Host.hsychang, '張琇茵'),  
    )

    host = models.PositiveSmallIntegerField(
    	verbose_name="接洽同仁",
        choices = HOST_CHOICES,
    )

    signature = models.TextField(max_length = 350000, default="")
    key = models.TextField(verbose_name="識別號碼",max_length=200, default=0)
    is_out = models.BooleanField(verbose_name="已簽退",default=True)
    login_time = models.DateTimeField(verbose_name="進入時間",default=timezone.now)
    logout_time = models.DateTimeField(verbose_name="離開時間",null=True, blank=True)
    host_key = models.TextField(verbose_name="確認拜訪同仁",max_length=200, null=True,blank=True)
    alter_key = models.TextField(verbose_name="代理確認拜訪同仁",max_length=200, null=True,blank=True)
    is_confirm = models.BooleanField(verbose_name="確認拜訪",default=False)
    class Meta:
        verbose_name_plural = "訪客紀錄"
    def __str__(self):
        return str(self.name)

signup/trips/forms.py
from django import forms
class VisitorForm(forms.Form):
    Name = forms.CharField(label='Name', max_length=100)
    Company = forms.CharField(label='Company', max_length=100)
    Purpose = forms.CharField(label='Company', max_length=100)

signup/trips/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.http import HttpResponseRedirect, JsonResponse
from .models import Visit_logs, Visitors, Organizations
from datetime import datetime
from django.template import RequestContext
import django.utils.timezone as timezone
import json
#import sys
#from importlib import reload

#reload(sys)
#sys.setdefaultencoding('utf-8')

# Create your views here.
def home(request):
	return render(request, 'trips/home.html', {})

def checkID(request):
	if request.method == "POST":
		ID = request.POST['ID']
		if not request.session.session_key:
			request.session.create()	
		request.session['ID'] = ID
		try: 
			result = Visitors.objects.get(personal_ID=ID)
		except Visitors.DoesNotExist:
			result = None
		if result:
			name = result.name
		else:
			name = "Not found"
		print("Get visitor name")
		return HttpResponse(json.dumps({'name': name}), content_type="application/json")
	return render(request,'trips/checkID.html',{})

def login(request):
	if request.method == "POST":
		#get request.POST and setup
		ID = request.session['ID']
		visitor = Visitors.objects.get(personal_ID=ID)
		Name = Visitors.objects.get(personal_ID=ID)
		print("Name.org_ID")
		Company = Organizations.objects.get(org_name=Name.org_ID.org_name)
		Purpose = request.POST['purpose']
		Signature = request.POST['url']
		Visit_area = request.POST['visit_area']
		Host = request.POST['host']
		Key = request.POST['key']
		Is_out = False
		Login_time = timezone.localtime()
		Logout_time = Login_time
		print(Login_time==Logout_time)
		#force logout
		try:
			result = Visit_logs.objects.filter(key=Key, is_out=False)
		except Visit_logs.DoesNotExist:
			result = None
		if result:
			print("key")
			Visit_logs.objects.filter(key=Key, is_out=False).update(is_out=True, logout_time=Logout_time)
		try:
			result = Visit_logs.objects.filter(name=Name, is_out=False)
		except Visit_logs.DoesNotExist:
			result = None
		if result:
			print("Name")
			Visit_logs.objects.filter(name=Name, is_out=False).update(is_out=True, logout_time=Logout_time)
		print("here")
		#save data
		log = Visit_logs(name=Name, company=Company, purpose=Purpose, visit_area=Visit_area, signature=Signature, host=Host, login_time=Login_time, key=Key, is_out=Is_out)
		log.save()
		print("Name", "key is", Key)
		return HttpResponse(json.dumps({'name': Name.name}), content_type="application/json")
	return render(request, 'trips/login.html',{})

def addID(request):
	if request.method=="POST":	
		Personal_ID = request.POST['ID']
		Name = request.POST['Name']
		Phone_number = request.POST['Phone_number']
		Email = request.POST['Email']
		Org_name = request.POST['org_Name']
		if not request.session.session_key:
			request.session.create()	
		request.session['ID'] = Personal_ID
		print("Get Post")
		if request.POST['new_Org_Name']=='':
			org = Organizations.objects.get(org_name=Org_name)
			print("Get exist org")
		else:
			new_Org_Name = request.POST['new_Org_Name']
			try:
				result = Organizations.objects.get(org_name=new_Org_Name)
				org = result
				print("org already exist")
			except Organizations.DoesNotExist:
				result = None
				FAX = request.POST['FAX']
				org = Organizations(org_name=new_Org_Name, FAX=FAX)
				org.save()
				print("Create org")
		try:
			exist = Visitors.objects.filter(personal_ID=Personal_ID)
			exist.update(name=Name, org_ID=org, phone_number=Phone_number, email=Email, personal_ID=Personal_ID)
			visit = Visitors.objects.get(personal_ID=Personal_ID)
			print("visitor already exist")
		except Visitors.DoesNotExist:
			visit = Visitors(name=Name, org_ID=org, phone_number=Phone_number, email=Email, personal_ID=Personal_ID)
			visit.save()
			print("Create visitor")
	all_objects = Organizations.objects.all()
	return render(request, 'trips/addID.html', {'all_objects':all_objects})

# def logout(request):
# 	if request.method == "POST":
# 		Logout_time = timezone.localtime()
# 		Key = request.POST['key']
# 		ID_lastfour = request.POST['ID']
# 		name = "Not found"
# 		check = False
# 		try: 
# 			result = Visit_logs.objects.get(key=Key, is_out=False)
# 		except Visit_logs.DoesNotExist:
# 			result = None
# 		if result:
# 			Name = result.name
# 			ID = Name.personal_ID
# 			if not request.session.session_key:
# 				request.session.create()	
# 			request.session['ID'] = ID
# 			if ID[-4:] == ID_lastfour:
# 				check = True
# 				print(Name.name, "use right qrcode and key is", Key)
# 				log = Visit_logs.objects.filter(name=Name).order_by('-login_time')[0]
# 				log.logout_time = Logout_time
# 				log.is_out = True
# 				log.save()
# 				name = Name.name
# 		print(name,check)
# 		return HttpResponse(json.dumps({'name': name, 'check': check}), content_type="application/json")
# 	return render(request, 'trips/logout.html',{})

def logout(request):
	if request.method == "POST":
		ID_lastfour = request.POST['ID']
		if ID_lastfour == "null" :
			name = "Not found"
			Key = request.POST['key']
			try:
				result = Visit_logs.objects.get(key=Key, is_out=False)
			except Visit_logs.DoesNotExist:
				result = None
			if result:
				Name = result.name
				name = Name.name
				print("got", "name")
			return HttpResponse(json.dumps({'name': name}), content_type="application/json")
		else :
			Logout_time = timezone.localtime()
			Key = request.POST['key']
			name = "Not found"
			check = False
			try: 
				result = Visit_logs.objects.get(key=Key, is_out=False)
			except Visit_logs.DoesNotExist:
				result = None
			if result:
				Name = result.name
				ID = Name.personal_ID
				if not request.session.session_key:
					request.session.create()	
				request.session['ID'] = ID
				if ID[-4:] == ID_lastfour:
					check = True
					print("Name.name", "use right qrcode and key is", Key)
					log = Visit_logs.objects.filter(name=Name).order_by('-login_time')[0]
					log.logout_time = Logout_time
					log.is_out = True
					log.save()
					name = Name.name
			print("name,check")
			return HttpResponse(json.dumps({'name': name, 'check': check}), content_type="application/json")
	return render(request, 'trips/logout.html',{})

def confirm(request):
	ID = request.session['ID']
	print("my ID is", ID)
	host = ""
	name = Visitors.objects.get(personal_ID=ID)
	if request.method == "POST":
		host = "Not found"
		key = int(request.POST['key'])
		result = Visit_logs.objects.get(name=name, is_out=False)
		print("host key is", key ,"and logs'host is", result.host)
		if key <= 20:
			if key == result.host:
				host = "host"
				result.host_key = key
				result.is_confirm = True
			else:
				host = "alter"
				result.alter_key = key
		print("host is", host)
		print(result.is_confirm)
		result.save()
		return HttpResponse(json.dumps({'host': host}), content_type="application/json")
	try: 
		result = Visit_logs.objects.get(name=name, is_out=False)
	except Visitors.DoesNotExist:
		result = None
	return render(request, 'trips/confirm.html',{'result':result})

def logout_confirm(request):
	ID = request.session['ID']
	name = Visitors.objects.get(personal_ID=ID)
	try: 
		result = Visit_logs.objects.filter(name=name).order_by('-logout_time')[0]
		print("result")
	except Visitors.DoesNotExist:
		result = None
	return render(request, 'trips/logout_confirm.html',{'result':result})




signup/trips/templates/trips/addID.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>訪客簽到流程</title>
	<meta charset="utf-8">
	<!-- Stylesheets -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"> -->
	<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/styles/mono-blue.min.css"> -->

	<!-- 	<link rel="stylesheet" href="{% static "bootstrap-4.1.1.min.css"%}"> -->
	<!-- 	<link rel="stylesheet" href="https://apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css"> -->
	<!-- 	<link rel="stylesheet" href="https://rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.css"> -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static "jquery-editable-select.min.css"%}">
	<link rel="stylesheet" href="{% static "jquery-ui.min.css"%}">
   	<link rel="stylesheet" href="{% static "trips/addID.css"%}">
   	<script type="text/javascript" src="{% static "trips/checkID.js"%}"></script>
</head>

<body onload="ShowTime()" style="background-color:#CCCCCC;">
	<div class="div_right_top"><a href="/">回首頁</a></div>
   <div class="loginmodal-container">
   		<div>
     	 <h1>訪客資料</h1><br>
			<table align="center">
				<tr><td width="110px">訪客姓名：</td><td><input type="text" id="Name" name="Name" placeholder="王大明" autocomplete="off" required/></td></tr>
				<tr><td >身分證字號：</td><td><input type="text" id="ID" name="ID" placeholder="A123456789" autocomplete="off" maxlength="10" minlegth="10"></td></tr>
				<tr><td>聯絡電話：</td><td><input type="tel" id="Phone_number" name="Phone_number" placeholder="0912345678" autocomplete="off" maxlength="10"/></td></tr>
				<tr><td>電子郵件：</td><td><input type="email" id="Email" name="Email" placeholder="example@gmail.com" autocomplete="off" maxlength="30"/></td></tr>
			
				<tr id="select_Org"><td>所屬單位：</td><td><select id="select" class="form-control" >
					{% for objects in all_objects %}
						<option>{{ objects.org_name }}</option>
					{% endfor %}
				</select></td></tr>
			</table>
			<div class="login-help" id="ask" align="center"> 
				<button id="add_Org" type="button" class="btn btn-link">無您所屬單位?</button>
			</div>
		</div>
		<div id="new_Org">
		<h1>所屬單位</h1><br>
			<table align="center">
				<tr><td width="110px">單位名稱：</td><td><input type="text" id="new_Org_Name" name="new_Org_Name" placeholder="STPI" autocomplete="off"/></td></tr>
				<tr><td>傳真號碼：</td><td><input type="text" id="Fax" name="Fax" placeholder="02-12345678" autocomplete="off" maxlength="11"/></td></tr>
			</table>
		</div>
		<input type="submit" id="submit" class="login loginmodal-submit" value="送出">
   </div>

   	<div id="dialog-modal" title="個資蒐集提醒事項">
	<ul>
		<li>本人已詳閱並瞭解政策中心<u>資訊系統組與電腦機房門禁管理辦法</u>相關規定與注意事項。</li>
		<li>本中心為達場所進出人員的安全管理之目的，搜集個人資料之類別為C001及C061，包含訪客的姓名、服務單位、及聯絡電話等資料。本中心將於營運期間及地區內以訪客個資作為安全管理之用，必要時，將利用訪客電話進行聯絡。訪客可以電洽本中心行使個資法第3條的當事人權利之程序。</li>
	</ul>
	</div>
	<div id="showbox" class="div_right_bottom"></div>

	<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
	<script src="https://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="https://apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
	<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script> -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/highlight.min.js"></script>
	<script src="https://rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.js"></script>
	<script>
		$(document).ready(function() {

		    $("#new_Org").hide();
		    var org_Name_Select = "";
		    var org_click = false;
		    $('#select').editableSelect().on('select.editable-select', function(e, li) {
		        $('#last-selected').html(li.val() + '. ' + li.text());
		        org_Name_Select = li.text();
		    });
		    $("#add_Org").click(function() {
		        $("#new_Org").show();
		        $("#select_Org").hide();
		        $("#ask").hide();
		        org_click = true;
		    });


		    $("#submit").click(function() {
		        var Name = document.getElementById("Name").value;
		        var ID = document.getElementById("ID").value;
		        var Phone_number = document.getElementById("Phone_number").value;
		        var Email = document.getElementById("Email").value;
		        var new_Org_Name = document.getElementById("new_Org_Name").value;
		        var Fax = document.getElementById("Fax").value;

		        if(!checkID(ID)){
		        	document.getElementById("ID").value = "";
		        	alert("請輸入正確的身分證字號");
		        	return false;
		        }
		        if ((Name == "") || (Phone_number == "") || (Email == "") || (ID == "")) {
		            alert("請輸入完整資訊");
		            return false;
		        } else if ((org_click == false) && (org_Name_Select == "")) {
		            alert("請輸入完整資訊");
		            return false;
		        } else if (org_click == true) {
		            if ((new_Org_Name == "") || (Fax == "")) {
		                alert("請輸入完整資訊");
		                return false;
		            } else {
		                $.ajax({
		                    type: "post",
		                    data: {
		                        org_Name: org_Name_Select,
		                        ID: ID,
		                        Name: Name,
		                        Phone_number: Phone_number,
		                        Email: Email,
		                        new_Org_Name: new_Org_Name,
		                        FAX: Fax,
		                        'csrfmiddlewaretoken': '{{ csrf_token }}',
		                    },
		                    success: function(data) {
		                        var message = "成功新增"+Name+"和"+new_Org_Name;
		                        alert(message);
		                        location.href = '{% url 'login' %}';
		                    }
		                });
		            }
		        } else {
		            $.ajax({
		                type: "post",
		                data: {
		                    org_Name: org_Name_Select,
		                    ID: ID,
		                    Name: Name,
		                    Phone_number: Phone_number,
		                    Email: Email,
		                    new_Org_Name: new_Org_Name,
		                    FAX: Fax,
		                    'csrfmiddlewaretoken': '{{ csrf_token }}',
		                },
		                success: function(data) {
		                    var message = "成功新增"+Name;
		                    alert(message);
		                    location.href = '{% url 'login' %}';
		                }
		            });
		        }
		    });

		
		});
	$(function() {
		$( "#dialog-modal" ).dialog({
			modal: true
		});
	});


	</script>
</body>

signup/trips/templates/trips/checkID.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
   <title>訪客簽到流程</title>
   <script src="{% static "jquery.min.js"%}"></script>
   <script src="{% static "jq-signature.js"%}"></script>
   <script src="{% static "jq-signature.min.js"%}"></script>
   <script type="text/javascript" src="{% static "adapter.min.js"%}"></script>
   <script type="text/javascript" src="{% static "vue.min.js"%}"></script>
   <script type="text/javascript" src="{% static "instascan.min.js"%}"></script>
   <link rel="stylesheet" href="{% static "trips/checkID.css"%}">
   <script type="text/javascript" src="{% static "trips/checkID.js"%}"></script>
</head>

<body onload="ShowTime()" style="background-color:#CCCCCC;">
  <div class="div_right_top">
    <a href="/">回首頁</a>
  </div>
  <div class="loginmodal-container">
    <center>
      <div style="font-size:30px;padding-bottom:50px; ">請輸入身分證字號</div>
    </center>
    <input id="ID" maxlength="10" name="ID" placeholder="A123456789" style="font-size:40px;height:90px;" type="text"> 
    <input class="login loginmodal-submit" id="send" name="login" type="submit" value="送出">
    <div class="login-help" style="font-size:20px;">
      第一次來訪請<a href="/addID" style="text-decoration:underline;">新增</a>
    </div>
  </div>
<div id="showbox" class="div_right_bottom"></div>
</body>

<script type="text/javascript">
   $(document).ready(function() {
       $("#send").click(function() {
           var value = document.getElementById("ID").value;
           if(!checkID(value)){
            document.getElementById("ID").value = "";
            alert("請輸入正確的身分證字號");
           }
           else{
            $.ajax({
               type: "post",
               data: {
                   ID: value,
                   'csrfmiddlewaretoken': '{{ csrf_token }}',
               },
               success: function(data) {
                   if (data.name != "Not found") {
                       var message = "請問你是" + data.name + "嗎？"
                       var check = confirm(message)
                       if (check) {
                           location.href = '{% url 'login' %}';
                       } else {
                           document.getElementById("ID").value = "";
                           alert("請重新填寫身分證字號");
                       }

                   } else {
                       document.getElementById("ID").value = "";
                       alert("查無此人資料，請重新填寫或點選新增按鈕");
                   }
               }
           });

           }//end else

       });
       $("#add").click(function() {
         location.href = "/addID";
       });
   });
</script>

</html>

signup/trips/templates/trips/confirm.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static "trips/confirm.css"%}">
<!--     <script type="text/javascript" src="{% static "trips/confirm.js"%}"></script> -->
    <script type="text/javascript" src="{% static "adapter.min.js" %}"></script>
    <script src="{% static "jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "vue.min.js" %}"></script>
    <script type="text/javascript" src="{% static "instascan.min.js" %}"></script>
    <script type="text/javascript" src="{% static "trips/checkID.js"%}"></script>
</head>



<body onload="ShowTime()" style="background-color:#CCCCCC;">
    <div class="div_right_top">
        <a href="/">回首頁</a>
    </div>
<!--   <div id = "show">
  </div> -->
<!--   <div style="background-color:#FFD382;padding:10px;margin-bottom:5px;">
  	<ul>
  		<li>本人已詳閱並瞭解政策中心<u>資訊系統組與電腦機房門禁管理辦法</u>相關規定與注意事項。</li>
  		<li>本中心為達場所進出人員的安全管理之目的，搜集個人資料之類別為C001及C061，包含訪客的姓名、服務單位、及聯絡電話等資料。本中心將於營運期間及地區內以訪客個資作為安全管理之用，必要時，將利用訪客電話進行聯絡。訪客可以電洽本中心行使個資法第3條的當事人權利之程序。</li>
  	</ul>
  	
  </div> -->
  <div style="text-align:center;">
  <h2>請相關同仁確認拜訪及資料</h2>
  <table>
    <tr>
      <th>姓名</th>
      <td>{{result.name}}</td>
      <th>服務單位</th>
      <td>{{result.company}}</td>
      <th>拜訪區域</th>
      <td>{{result.get_visit_area_display}}</td>
    </tr>
    <tr> 
      <th>拜訪目的</th>
      <td>{{result.get_purpose_display}}</td>
      <th>接洽同仁</th>
      <td>{{result.get_host_display}}</td>
      <th>簽到時間</th>
      <td><font color="red">{{result.login_time|date:'Y-m-d H:i'}}</font></td>
    </tr>

  </table>
  </div>
  <center>
    <h5></h5>
    <div class="preview-container">
      <video id="preview"></video>
    </div>
  </center>
  <div class="div_right_bottom" id="showbox"></div>
</div>

</body>
        <script type="text/javascript">
        var app = new Vue({
        delimiters: ['{', '}'],
        el: '#app',
        data: {
            scanner: null,
            activeCameraId: null,
            cameras: [],
            scans: []
        },
        mounted: function() {
            var self = this;
            var pk = document.getElementById("myVar");
            self.scanner = new Instascan.Scanner({
                video: document.getElementById('preview'),
                scanPeriod: 5
            });
            self.scanner.addListener('scan', function(content, image) {
                self.scans.unshift({
                    date: +(Date.now()),
                    content: content
                });
                $.post("", {
                        'key': content,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    function(data, status) {
                        if (data.host != "Not found") {
                            if ( data.host=="host") {
                            	alert("同仁已確認拜訪");
                                location.href = "/";
                            } else {
           			alert("代理同仁已確認拜訪");
				location.href = "/";
			    }
                        } else {
                            alert("請輸入正確的 QR code ");
                            return false;
                        }
                    });
            });
            Instascan.Camera.getCameras().then(function(cameras) {
                self.cameras = cameras;
                if (cameras.length > 0) {
                    self.activeCameraId = cameras[0].id;
                    self.scanner.start(cameras[0]);
                } else {
                    console.error('No cameras found.');
                }
            }).catch(function(e) {
                console.error(e);
            });

        },
        methods: {}
    });


    </script>
</html>

signup/trips/templates/trips/logout_confirm.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static "trips/confirm.css"%}">
    <script type="text/javascript" src="{% static "trips/confirm.js"%}"></script>
</head>

<body style="background-color:#CCCCCC;">
  <div id = "show">
  </div>
  <div style="background-color:#FFD382;padding:10px;margin-bottom:5px;">
  	<ul>
  		<li>本人已詳閱並瞭解政策中心<u>資訊系統組與電腦機房門禁管理辦法</u>相關規定與注意事項。</li>
  		<li>本中心為達場所進出人員的安全管理之目的，搜集個人資料之類別為C001及C061，包含訪客的姓名、服務單位、及聯絡電話等資料。本中心將於營運期間及地區內以訪客個資作為安全管理之用，必要時，將利用訪客電話進行聯絡。訪客可以電洽本中心行使個資法第3條的當事人權利之程序。</li>
  	</ul>
  	
  </div>
  <div>
  	<h1>請確認資料</h1>
  <table>
    <tr>
      <th>姓名</th>
      <td>{{result.name}}</td>
    </tr>
    <tr>
      <th>服務單位</th>
      <td>{{result.company}}</td>
    </tr>
    <tr>
      <th>拜訪區域</th>
      <td>{{result.get_visit_area_display}}</td>
    </tr>
    <tr>
      <th>拜訪目的</th>
      <td>{{result.get_purpose_display}}</td>
    </tr>
    <tr>
      <th>接洽同仁</th>
      <td>{{result.get_host_display}}</td>
    </tr>
    <tr>
      <th>簽到時間</th>
      <td><font color="red">{{result.login_time|date:'Y-m-d H:i'}}</font></td>
    </tr>
     <tr>
      <th>簽退時間</th>
      {% if result.logout_time|date:'Y-m-d H:i:s' == "" %}
      <td>尚未簽退</font></td>
      {% else %}
      <td><font color="red">{{result.logout_time|date:'Y-m-d H:i'}}</font></td>
      {% endif %}
    </tr> 
    
  </table>
</div>
</body>
</html>